[package]
name = "clapier-flash"
description = "Firmware flasher for the Nabaztag:tag bootloader"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[[bin]]
name = "flash-nabaztag"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
socket2.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
